config = "release"
default-linker = "gold"
reference-repositories = "/reference-repos"

[uri-schemes]
"github://" = "https://github.com/"
"laboratory://" = "https://laboratory.comsys.rwth-aachen.de/"
