variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: eyrie.comsys.rwth-aachen.de

image: docker:dind

before_script:
  - echo $CI_JOB_ID
  - echo $CI_RUNNER_ID
  - echo $CI_RUNNER_REVISION
  - echo $CI_RUNNER_TAGS
  - echo $CI_RUNNER_VERSION
  - echo $CI_RUNNER_DESCRIPTION
  - 'dockerd-entrypoint.sh >/dev/null 2>&1 &'
  - 'DOCKERD_PID="$(jobs -l -p)"'
  - 'function kill_and_wait_for_docker { kill "$DOCKERD_PID" ; wait "$DOCKERD_PID" ; echo dockerd terminated gracefully ; }'
  - 'while if docker ps >/dev/null 2>&1 ; then false ; else true ; fi do echo waiting for dockerd startup... ; sleep 1 ; done'
  - 'trap kill_and_wait_for_docker EXIT'
  - 'echo started dockerd with driver "\"$DOCKER_DRIVER\""'

stages:
  - build-image
  - build-ws

build-image:
  stage: build-image
  # artifacts:
  #   paths:
  #     - ci-image.tar.bz2
  #   expire_in: 1 hour
  script:
    - docker info
    - echo "$CI_PROJECT_NAME"
    - echo "$CI_PROJECT_NAMESPACE"
    - echo "$CI_PROJECT_PATH"
    - echo "$CI_PROJECT_PATH_SLUG"
    - apk add bzip2
    - docker build -f .gitlab-ci-src/Dockerfile -t ci-image .
    # - docker save ci-image:latest | bzip2 > ci-image.tar.bz2
    - docker run --name ci-building -v /ccache:/ccache -v /cache:/cache ci-image /usr/bin/bash -c './ws build -j8'
    - docker commit ci-building symbiosis/workspace_base-ci:latest
    - docker login -u $DOCKER_CI_USER -p $DOCKER_CI_AUTH $DOCKER_REGISTRY
    - docker push symbiosis/workspace_base-ci:latest

# build-ws:
#   stage: build-ws
#   dependencies:
#     - build-image
#   script:
#     - bunzip2 -c ci-image.tar.bz2 | docker load
#     - docker run --name ci-building -v /ccache:/ccache -v /cache:/cache ci-image /usr/bin/bash -c './ws build -j8'
#     - docker commit ci-building symbiosis/workspace_base-ci:latest
#     - docker login -u $DOCKER_CI_USER -p $DOCKER_CI_AUTH $DOCKER_REGISTRY
#     - docker push symbiosis/workspace_base-ci:latest
