variables:
  WS_JOBS: 3 # the (required) runner only allows 3 cores to be used per job
  DOCKER_REGISTRY: eyrie.comsys.rwth-aachen.de
  IMAGE_NAME: $DOCKER_REGISTRY/$CI_PROJECT_PATH_SLUG

before_script:
  - echo $CI_JOB_ID
  - echo $CI_RUNNER_ID
  - echo $CI_RUNNER_REVISION
  - echo $CI_RUNNER_TAGS
  - echo $CI_RUNNER_VERSION
  - echo $CI_RUNNER_DESCRIPTION
  - echo "$CI_PROJECT_NAME"
  - echo "$CI_PROJECT_NAMESPACE"
  - echo "$CI_PROJECT_PATH"
  - echo "$CI_PROJECT_PATH_SLUG"
  - echo "$CI_COMMIT_REF_NAME"
  - echo "$CI_COMMIT_REF_SLUG"
  - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
  - echo "$CI_MERGE_REQUEST_TITLE"
  - echo "${WS_JOBS:-auto}"

stages:
  - build

lint:
  stage: build
  image: kennethreitz/pipenv
  script:
    - ws-src/mypy_check.sh
    - ws-src/pylint_check.sh
    - ws-src/yapf_check.sh || (echo && echo Code not properly formatted - run ws-src/yapf_format.sh! && false)

build-not-master:
  stage: build
  image: docker:dind
  artifacts:
    paths:
      - build.log
    expire_in: 1 day
  except:
    refs:
      - master
  script:
    - 'source .gitlab-ci-src/setup_dind.sh'

    - 'docker build --cache-from=$IMAGE_NAME:latest -f .gitlab-ci-src/Dockerfile -t base .'
    - 'docker run --name sources -v ~/netrc:/root/netrc base ./ws setup'
    - 'EXPIRY=$(date -d@"$(( $(date -u +%s)+60*60*24 ))" +%Y-%m-%dT%H:%M:%SZ)' # compute date of tomorrow with the alpine busybox date command
    - 'docker commit --change "LABEL comsys.ExpireDate=$EXPIRY" --change "CMD bash" sources $IMAGE_NAME:$CI_COMMIT_SHA'
    - '( docker push $IMAGE_NAME:CI_COMMIT_SHA &
      if [[ -z "$DOCKER_SAVE" ]] ; then
        docker save $IMAGE_NAME:latest | zstd -T${WS_JOBS:-0} -2 >/cache/image.tar.zst ;
        echo Saved new copy of $IMAGE_NAME:latest to cache ;
      fi ;
      wait)'
    - 'echo "Successfully pushed $IMAGE_NAME:$CI_COMMIT_SHA (expires at $EXPIRY)"'

    - 'docker run --name ci -v /ccache:/ccache $IMAGE_NAME:$CI_COMMIT_SHA ./ws build > build.log'

build-master:
  stage: build
  image: docker:dind
  artifacts:
    paths:
      - build.log
    expire_in: 1 day
  only:
    refs:
      - master
  script:
    - 'source .gitlab-ci-src/setup_dind.sh'

    - 'docker build --cache-from=$IMAGE_NAME:latest -f .gitlab-ci-src/Dockerfile -t base .'
    - 'docker run --name sources -v ~/netrc:/root/netrc base ./ws setup --reference-repositories=/cache/reference-repos --X-git-clone=--dissociate --X-git-clone=--depth=1'
    - 'docker commit sources $IMAGE_NAME:latest'
    - '( docker push $IMAGE_NAME:latest &
      docker save $IMAGE_NAME:latest | zstd -T${WS_JOBS:-0} -2 >/cache/image.tar.zst
      echo Saved new copy of $IMAGE_NAME:latest to cache
      wait)'
    - 'echo "Successfully pushed $IMAGE_NAME:latest"'

    - 'docker run --name ci -v /ccache:/ccache $IMAGE_NAME:latest ./ws build > build.log'
    - 'docker commit ci $IMAGE_NAME:latest-prebuilt'
    - 'docker push $IMAGE_NAME:latest-prebuilt'
    - 'echo "Successfully pushed $IMAGE_NAME:latest-prebuilt"'
