[[LLVM]]
branch = "release_70"
profile = "release"

# [[LLVM]]
# name = "llvm-debug"
# branch = "release_70"
# profile = "release"

[[Z3]]
branch = "z3-4.8.1"
profile = "release"

[[MINISAT]]
branch = "master"

[[STP]]
branch = "master"

[[KLEE_UCLIBC]]
branch = "klee_0_9_29"

[[KLEE]]
branch = "master"
profile = "release"
