[[LLVM]]
branch = "llvmorg-7.0.1"
profile = "release"

[[Z3]]
branch = "z3-4.8.4"
profile = "release"

[[MINISAT]]
branch = "master"

[[STP]]
branch = "master"

[[KLEE_UCLIBC]]
branch = "klee_0_9_29"

[[SIMULATOR]]
branch = "master"
profile = "release"

[[PORSE]]
branch = "master"
profile = "release"
