[[Recipe]]
recipe = "Z3"
name = "z3"
branch = "z3-4.8.7"
profile = "rel+debinfo"
shared = false
thread-safe = false

[[Recipe]]
recipe = "LLVM"
name = "llvm"
branch = "llvmorg-9.0.1"
profile = "rel+debinfo"

[[Recipe]]
recipe = "KLEE_LIBCXXABI"
name = "klee-libcxxabi"
branch = "llvmorg-9.0.0"
profile = "rel+debinfo"

[[Recipe]]
recipe = "KLEE_LIBCXX"
name = "klee-libcxx"
profile = "rel+debinfo"

[[Recipe]]
recipe = "MINISAT"
name = "minisat"
branch = "releases/2.2.1"

[[Recipe]]
recipe = "STP"
name = "stp"
branch = "2.3.3"
profile = "rel+debinfo"

[[Recipe]]
recipe = "KLEE_UCLIBC"
name = "klee-uclibc"
branch = "klee_0_9_29"

[[Recipe]]
recipe = "KLEE"
name = "klee"
branch = "master"
profile = "rel+debinfo"
klee-libcxx = "klee-libcxx"
