[[Recipe]]
recipe = "LLVM"
branch = "llvmorg-8.0.1"
profile = "rel+debinfo"

[[Recipe]]
recipe = "Z3"
branch = "Z3-4.8.5"
profile = "rel+debinfo"
openmp = false

[[Recipe]]
recipe = "MINISAT"
branch = "releases/2.2.1"

[[Recipe]]
recipe = "STP"
branch = "2.3.3"
profile = "rel+debinfo"

[[Recipe]]
recipe = "KLEE_UCLIBC"
branch = "klee_0_9_29"

[[Recipe]]
recipe = "KLEE"
branch = "master"
profile = "rel+debinfo"
