[[LLVM]]
branch = "llvmorg-8.0.1"
profile = "release"

[[Z3]]
branch = "Z3-4.8.5"
profile = "release"
openmp = false

[[MINISAT]]
branch = "releases/2.2.1"

[[STP]]
branch = "2.3.3"
profile = "release"

[[KLEE_UCLIBC]]
branch = "klee_0_9_29"

[[SIMULATOR]]
branch = "master"
profile = "release"

[[PSEUDOALLOC]]
branch = "master"
profile = "release"

[[PORSE]]
branch = "master"
profile = "release"
