[[LLVM]]
branch = "llvmorg-8.0.0"
profile = "release"

[[Z3]]
branch = "Z3-4.8.5"
profile = "release"

[[MINISAT]]
branch = "master"

[[STP]]
branch = "2.3.3"
profile = "release"

[[KLEE_UCLIBC]]
branch = "klee_0_9_29"

[[KLEE]]
branch = "master"
profile = "release"
