[[Recipe]]
recipe = "Z3"
name = "z3"
branch = "z3-4.8.6"
profile = "release"
shared = false
openmp = false

[[Recipe]]
recipe = "LLVM"
name = "llvm"
branch = "llvmorg-8.0.1"
profile = "release"

[[Recipe]]
recipe = "KLEE_LIBCXXABI"
name = "klee-libcxxabi"
branch = "llvmorg-8.0.1"
profile = "release"

[[Recipe]]
recipe = "KLEE_LIBCXX"
name = "klee-libcxx"
profile = "release"

[[Recipe]]
recipe = "MINISAT"
name = "minisat"
branch = "releases/2.2.1"

[[Recipe]]
recipe = "STP"
name = "stp"
branch = "2.3.3"
profile = "release"

[[Recipe]]
recipe = "KLEE_UCLIBC"
name = "klee-uclibc"
branch = "klee_0_9_29"

[[Recipe]]
recipe = "SIMULATOR"
name = "simulator"
branch = "master"
profile = "release"

[[Recipe]]
recipe = "PSEUDOALLOC"
name = "pseudoalloc"
branch = "master"
profile = "release"

[[Recipe]]
recipe = "PORSE"
name = "porse"
branch = "master"
profile = "release"
klee-libcxx = "klee-libcxx"
