[[LLVM]]
branch = "llvmorg-8.0.1"
profile = "rel+debinfo"

[[Z3]]
branch = "Z3-4.8.5"
profile = "rel+debinfo"
openmp = false

[[MINISAT]]
branch = "releases/2.2.1"

[[STP]]
branch = "2.3.3"
profile = "rel+debinfo"

[[KLEE_UCLIBC]]
branch = "klee_0_9_29"

[[KLEE]]
branch = "master"
profile = "sanitized"
