[[Recipe]]
recipe = "Z3"
name = "z3"
branch = "z3-4.8.7"
profile = "rel+debinfo"
shared = false
thread-safe = false

[[Recipe]]
recipe = "LLVM"
name = "llvm"
branch = "llvmorg-9.0.0"
profile = "debug"

[[Recipe]]
recipe = "MINISAT"
name = "minisat"
branch = "releases/2.2.1"

[[Recipe]]
recipe = "STP"
name = "stp"
branch = "2.3.3"
profile = "rel+debinfo"

[[Recipe]]
recipe = "KLEE_UCLIBC"
name = "klee-uclibc"
branch = "klee_0_9_29"
repository = "laboratory://symbiosys/projects/concurrent-symbolic-execution/klee-uclibc.git"

[[Recipe]]
recipe = "SIMULATOR"
name = "simulator"
branch = "master"
profile = "debug"

[[Recipe]]
recipe = "PSEUDOALLOC"
name = "pseudoalloc"
branch = "master"
profile = "debug"

[[Recipe]]
recipe = "PORSE"
name = "porse"
branch = "master"
profile = "debug"
# WARNING: this is very memory intensive, even for small example programs
cmake-adjustments = ["-DVERIFIED_FINGERPRINTS=On"]
