[[Recipe]]
recipe = "Z3"
name = "z3"
branch = "z3-4.8.7"
profile = "rel+debinfo"
shared = false
thread-safe = false

[[Recipe]]
recipe = "LLVM"
name = "llvm"
branch = "llvmorg-9.0.1"
profile = "rel+debinfo"

[[Recipe]]
recipe = "KLEE_LIBCXXABI"
name = "klee-libcxxabi"
branch = "llvmorg-9.0.1"
profile = "release"

[[Recipe]]
recipe = "KLEE_LIBCXX"
name = "klee-libcxx"
profile = "release"

[[Recipe]]
recipe = "MINISAT"
name = "minisat"
branch = "releases/2.2.1"

[[Recipe]]
recipe = "STP"
name = "stp"
branch = "2.3.3"
profile = "rel+debinfo"

[[Recipe]]
recipe = "KLEE_UCLIBC"
name = "klee-uclibc"
branch = "klee_0_9_29"
repository = "laboratory://symbiosys/projects/concurrent-symbolic-execution/klee-uclibc.git"

[[Recipe]]
recipe = "SIMULATOR"
name = "simulator"
branch = "master"
profile = "rel+debinfo"
porse = "porse"
expensive-checks = false
verified-fingerprints = true

[[Recipe]]
recipe = "PSEUDOALLOC"
name = "pseudoalloc"
branch = "master"
profile = "rel+debinfo"

[[Recipe]]
recipe = "PORSE"
name = "porse"
branch = "master"
profile = "rel+debinfo"
klee-libcxx = "klee-libcxx"
# WARNING: this is very memory intensive, even for small example programs
verified-fingerprints = true
