[[Recipe]]
recipe = "Z3"
name = "z3"
branch = "Z3-4.8.5"
profile = "rel+debinfo"
shared = false
openmp = false

[[Recipe]]
recipe = "LLVM"
name = "llvm"
branch = "llvmorg-8.0.1"
profile = "rel+debinfo"

[[Recipe]]
recipe = "MINISAT"
name = "minisat"
branch = "releases/2.2.1"

[[Recipe]]
recipe = "STP"
name = "stp"
branch = "2.3.3"
profile = "rel+debinfo"

[[Recipe]]
recipe = "KLEE_UCLIBC"
name = "klee-uclibc"
branch = "klee_0_9_29"

[[Recipe]]
recipe = "SIMULATOR"
name = "simulator"
branch = "master"
profile = "rel+debinfo"

[[Recipe]]
recipe = "PSEUDOALLOC"
name = "pseudoalloc"
branch = "master"
profile = "rel+debinfo"

[[Recipe]]
recipe = "PORSE"
name = "porse"
branch = "master"
profile = "rel+debinfo"
# WARNING: this is very memory intensive, even for small example programs
cmake-adjustments = ["-DVERIFIED_FINGERPRINTS=On"]
